version: "3.8"

services:
  kubectl-cli-paas:
    container_name: cli
    env_file:
      - .env
    build: .
    volumes:
    - "./.aws/:${VOLUME_CREDENTIALS_AWS}"
    - "./.config/:${VOLUME_CREDENTIALS_DIGITALOCEAN}"